### ISSUE TITLE
Hocam genel ortalama hesap lütfen

### ISSUE THREAD

**Issue by HyoAkira** [serkan-bayram/obs-calculator#1]
elleriniz dert görmesin ben üşeniyom

**Comment by serkan-bayram** [comment]
> elleriniz dert görmesin ben üşeniyom

Notlar açıklanınca kod patladı hocam acil community desteği lazım bu projeye

**Comment by HyoAkira** [comment]
boş olduğumda genel ortalama hesaplama eklicem. commitlerim.

Paşa gösterdi geçme kalma notu hesaplıyor, biraz traşlayıp eklenir.

gereken bir proje, veririz destek hocam.
